/*
 *  Copyright 2019 pixiv Inc. All Rights Reserved.
 *
 *  Use of this source code is governed by a license that can be
 *  found in the LICENSE.pixiv file in the root of the source tree.
 */

#include "sdk/c/api/video/video_buffer.h"
#include "sdk/c/api/video/video_frame.h"
#include "sdk/c/api/video/video_rotation.h"
#include "sdk/c/api/video/video_frame_buffer.h"
#include "sdk/c/api/video/color_space.h"
#include "sdk/c/api/video/i420_buffer.h"
#include "sdk/c/api/video/video_bitrate_allocator_factory.h"
#include "sdk/c/api/video/video_sink_interface.h"
#include "sdk/c/api/audio_codecs.h"
#include "sdk/c/api/create_peerconnection_factory.h"
#include "sdk/c/api/create_turn_server.h"
#include "sdk/c/api/data_channel_interface.h"
#include "sdk/c/api/jsep.h"
#include "sdk/c/api/rtc_error.h"
#include "sdk/c/api/media_stream_interface.h"
#include "sdk/c/api/peer_connection_interface.h"
#include "sdk/c/api/rtp_receiver_interface.h"
#include "sdk/c/api/rtp_sender_interface.h"
#include "sdk/c/api/rtp_transceiver_interface.h"
#include "sdk/c/api/video_codecs.h"
#include "sdk/c/api/audio.h"
#include "sdk/c/api/async_resolver_factory.h"
#include "sdk/c/api/candidate.h"
#include "sdk/c/media/base/adapted_video_track_source.h"
#include "sdk/c/media/base/media_engine.h"
#include "sdk/c/media/base/video_adapter.h"
#include "sdk/c/common_video/libyuv.h"
#include "sdk/c/modules/audio_device.h"
#include "sdk/c/modules/audio_processing.h"
#include "sdk/c/rtc_base/message_queue.h"
#include "sdk/c/rtc_base/rtc_certificate_generator.h"
#include "sdk/c/rtc_base/rtc_certificate.h"
#include "sdk/c/rtc_base/ssl_certificate.h"
#include "sdk/c/rtc_base/thread.h"
#include "sdk/c/interop.h"
#include "sdk/c/p2p/base.h"
